### ISSUE TITLE
Option to pre-install gitlab-runner inside the VMs

### ISSUE THREAD

**Issue by fkorotkov** [cirruslabs/gitlab-tart-executor#1]
Executor should have a flag that will make it to check existence of `gitlab-runner` being installed inside the VM so cache/artifacts uploads are working.

It's probably fair to check for both `brew` being presented as well to simplify installation via `brew install gitlab-runner`.

**Comment by theoriginalgri** [comment]
Just wanted to comment that it would be great to have this in the base images and then realized you already changed that in https://github.com/cirruslabs/macos-image-templates/commit/5828bf5b7ca7c6e9d07edff2580112b33be6b793 👍

**Comment by fkorotkov** [comment]
Yes, I did. 😅 This option might be useful for custom images... but people can also install it I. Custom images themselves. So this issue is not crucial but probably good to have at some point.
