### ISSUE TITLE
Default Image

### ISSUE THREAD

**Issue by RLovelett** [cirruslabs/gitlab-tart-executor#19]
Is it possible to configure a "default" image similar to how the Docker executor has an `image` property in the `config.toml`?

I am running into [this code](https://github.com/cirruslabs/gitlab-tart-executor/blob/7fdce5aff1aaf17f360a46d87fef32dd526ff751/internal/gitlab/env.go#L42-L45).

```go
jobImage, ok := os.LookupEnv("CUSTOM_ENV_CI_JOB_IMAGE")
if !ok {
    return nil, fmt.Errorf("%w: CUSTOM_ENV_CI_JOB_IMAGE is missing", ErrGitLabEnv)
}
```

It would be nice to provide a default image, possibly as an environment variable or argument, that way we do not have to modify each of our `.gitlab-ci.yml` as we transition to Tart.

**Comment by RLovelett** [comment]
I've made a patch, [19-default-image.patch](https://github.com/cirruslabs/gitlab-tart-executor/files/11431822/19-default-image.patch), that I believe accomplishes my request.

```patch
diff --git a/internal/gitlab/env.go b/internal/gitlab/env.go
index fa54bd5..2fcd2b4 100644
--- a/internal/gitlab/env.go
+++ b/internal/gitlab/env.go
@@ -31,7 +31,7 @@ func (e Env) HostDirPath() string {
 	return filepath.Join(os.TempDir(), fmt.Sprintf("tart-executor-host-dir-%s", e.JobID))
 }

-func InitEnv() (*Env, error) {
+func InitEnv(defaultImage string) (*Env, error) {
 	result := &Env{}
 	jobID, ok := os.LookupEnv("CUSTOM_ENV_CI_JOB_ID")
 	if !ok {
@@ -41,7 +41,10 @@ func InitEnv() (*Env, error) {
 	result.JobID = jobID
 	jobImage, ok := os.LookupEnv("CUSTOM_ENV_CI_JOB_IMAGE")
 	if !ok {
-		return nil, fmt.Errorf("%w: CUSTOM_ENV_CI_JOB_IMAGE is missing", ErrGitLabEnv)
+		if defaultImage == "" {
+			return nil, fmt.Errorf("%w: CUSTOM_ENV_CI_JOB_IMAGE and CUSTOM_ENV_TART_EXECUTOR_DEFAULT_IMAGE are both missing", ErrGitLabEnv)
+		}
+		jobImage = defaultImage
 	}
 ```

**Comment by edigaryev** [comment]
Would setting the `CI_JOB_IMAGE` environment variable instead solve the issue? 🤔

**Comment by RLovelett** [comment]
So the odyssey is continuing. The only reason why I started to look into this was that I wanted to set `CUSTOM_ENV_CI_JOB_IMAGE` in the `config.toml` file and have it work; it did not.

I was hoping (and now learning I misunderstood) that I would be able to set `CUSTOM_ENV_TART_EXECUTOR_DEFAULT_IMAGE` in the `config.toml` and have that work; it did not. I had to add `CUSTOM_ENV_TART_EXECUTOR_DEFAULT_IMAGE` to the `gitlab-runner`'s environment to make it work. After seeing your suggestion it occurred to me that I needed to use `TART_EXECUTOR_DEFAULT_IMAGE` to make mine work; it did.

However setting just `CI_JOB_IMAGE` in the `config.toml` does work. In the end that is what I want. The only concern I have is that in the future when we start setting it in the `.gitlab-ci.yml` file will it over ride the one in `config.toml`? Hopefully.

For now this keeps me moving forward and I will close this.

Thanks for the suggestion.

**Comment by edigaryev** [comment]
> The only concern I have is that in the future when we start setting it in the `.gitlab-ci.yml` file will it over ride the one in `config.toml`?

Project variables seem to override `.gitlab-ci.yml` variables, according to [CI/CD variable precedence](https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence).
