### ISSUE TITLE
tart pull causes a 403 AuthFailed error

### ISSUE THREAD

**Issue by JulianH** [cirruslabs/gitlab-tart-executor#28]
Hello,

i get an unexpected error when try to run a Gitlab job using a tart image:
```
Running with gitlab-runner 15.10.1 (dcfb4b66)
  on tart-on-wrkmac03.local 8v2GZgty
  feature flags: FF_RESOLVE_FULL_TLS_CHAIN:false
Preparing the "custom" executor
Using Custom executor...
 Pulling the latest version of ghcr.io/cirruslabs/macos-ventura-xcode:14.3.1...
 tart command returned non-zero exit code: "Error: AuthFailed(why: \"received unexpected HTTP status code 403 while retrieving an authentication token\", details: \"{\\\"errors\\\":[{\\\"code\\\":\\\"DENIED\\\",\\\"message\\\":\\\"denied\\\"}]}\\n\")"
WARNING: Cleanup script failed: exit status 1
ERROR: Job failed: exit status 1
``` 

If try to do manually a `tart pull ...`, everything is working fine.

**Comment by fkorotkov** [comment]
Have you `tart login` before? Maybe credentials have expired. Could you please try to go to Keychain and look for "Tart Credentials" and delete them.

**Comment by JulianH** [comment]
> Have you `tart login` before? Maybe credentials have expired. Could you please try to go to Keychain and look for "Tart Credentials" and delete them.

Hi @fkorotkov, no i didn't used that command before. Also i cannot find any entry in the Keychain related to `tart`.

**Comment by edigaryev** [comment]
Please check out the [new version of GitLab Tart Executor](https://github.com/cirruslabs/gitlab-tart-executor/releases/tag/1.4.1) that includes support for [`TART_REGISTRY_HOSTNAME`](https://github.com/cirruslabs/gitlab-tart-executor/pull/29).

This will also require the [new Tart version](https://github.com/cirruslabs/tart/releases/tag/1.8.3) to work properly.

With this change, Tart won't try to use GitLab CI Registry's provided credentials for `ghcr.io` and other registries, which in turn should solve your issue.
