### ISSUE TITLE
Tart execution reports no IP available

### ISSUE THREAD

**Issue by jlarmstrong** [cirruslabs/gitlab-tart-executor#30]
I am seeing both with local already existing images and with images pulling from github that the gitlab-tart-executor is not seeing the VM startup within the timeout. Is there any additional logging that is not documented that can help troubleshoot this behavior currently? The gitlab tart custom executor is running on an AWS instance with an EBS volume. Manually testing the clone/startup/ip resolution time appears that I'm not seeing an IP resolve for 54 seconds consistently.

Using an image that already has been pulled:
```
Using Custom executor...
82023/07/07 12:50:48 Cloning and configuring a new VM...
92023/07/07 12:50:48 Waiting for the VM to boot and be SSH-able...
102023/07/07 12:51:49 tart command returned non-zero exit code: "no IP address found, is your VM running?"
```

Using the cirruslabs image:
```
Using Custom executor...
82023/07/07 12:49:27 Pulling the latest version of ghcr.io/cirruslabs/macos-ventura-xcode:14.3.1...
92023/07/07 12:49:27 Cloning and configuring a new VM...
102023/07/07 12:49:27 Waiting for the VM to boot and be SSH-able...
112023/07/07 12:50:28 tart command returned non-zero exit code: "no IP address found, is your VM running?"
```

Secondarily the tart pull step is not always showing the image within the `tart list` oci entries after we prune the system of previous images and try the process again. 

**Versions:**
Tart: 1.8.0
Gitlab executor: 15.8.2
Gitlab Tart Executor: 1.4.0

**Comment by edigaryev** [comment]
Hello Jared! Thanks for reporting this.

I've created https://github.com/cirruslabs/gitlab-tart-executor/pull/32 to help figure out the root cause.

Meanwhile, could you try updating Tart to the latest version (`1.8.4`)?

There were [some changes recently](https://github.com/cirruslabs/tart/pull/553) that might fix your issue.

**Comment by edigaryev** [comment]
A new GitLab Tart Executor version is now available: https://github.com/cirruslabs/gitlab-tart-executor/releases/tag/1.4.2.

Please try running your job with it again, it should highlight the underlying issue in logs.

**Comment by jlarmstrong** [comment]
With the latest updates I'm not seeing:
```
2023/07/14 12:11:24 Pulling the latest version of ghcr.io/cirruslabs/macos-ventura-xcode:14.3.1...
2023/07/14 12:11:25 Cloning and configuring a new VM...
2023/07/14 12:11:25 Waiting for the VM to boot and be SSH-able...
nohup: can't detach from console: Inappropriate ioctl for device
2023/07/14 12:24:46 VM errored: failed to connect via SSH: All attempts fail:
#1: dial tcp 192.168.64.7:22: connect: operation timed out
#2: dial tcp 192.168.64.7:22: connect: operation timed out
#3: dial tcp 192.168.64.7:22: connect: operation timed out
#4: dial tcp 192.168.64.7:22: connect: operation timed out
#5: dial tcp 192.168.64.7:22: connect: operation timed out
#6: dial tcp 192.168.64.7:22: connect: operation timed out
#7: dial tcp 192.168.64.7:22: connect: operation timed out
#8: dial tcp 192.168.64.7:22: connect: operation timed out
#9: dial tcp 192.168.64.7:22: connect: operation timed out
#10: dial tcp 192.168.64.7:22: connect: operation timed out
```

If we vm pull, vm clone, vm start, we can SSH into the system and confirm outbound traffic through the VM.

**Comment by edigaryev** [comment]
@jlarmstrong please check out the [new `1.4.3` release](https://github.com/cirruslabs/gitlab-tart-executor/releases/tag/1.4.3) which should fix your issue 🙌
