### ISSUE TITLE
supposed network problem between the vm and the host

### ISSUE THREAD

**Issue by macrozone** [cirruslabs/gitlab-tart-executor#34]
i am trying to add gitlab-tart-executor.

i managed to get it running as a gitlab-runner, but for my repo it often hangs during git fetch:

```
Created fresh repository.
```

and after some time it fails with:

```
error: RPC failed; curl 56 Recv failure: Operation timed out
error: 18 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output
```

i _sometimes_ managed to get it through, but then any `yarn install` has also problems fetching stuff

so i suppose its some network problem (maybe mtu?)

anyone got an idea?

**Comment by fkorotkov** [comment]
Do you have any VPN installed on the host? Or some other non standard network configuration?

**Comment by macrozone** [comment]
> Do you have any VPN installed on the host? Or some other non standard network configuration?

no, its freshly installed mac mini M2, the host user running the gitlab-runner is a non-admin.

what is weird is that if get a shell into the tart machine and try git pull, it also hangs, but not consistently and sometimes goes though. So its very inconsistent

It reminds me a bit on some mtu problem that google cloud once had with docker-in-docker builds...

**Comment by fkorotkov** [comment]
Where do you host your Mac Mini? 

Could you also try just running a tart vm without the executor and experiment with 'tart run --net-softnet'? Which will use https://github.com/cirruslabs/softnet. Maybe even try '--net-bridged'?
