### ISSUE TITLE
Missing Xamarin.iOS assets

### ISSUE THREAD

**Issue by Hackmodford** [cirruslabs/gitlab-tart-executor#38]
Does the gitlab executor create symlinks for the build dir?
Apparently msbuild has issues generating the iOS asset catalog if its in a symlinked dir.
https://github.com/xamarin/xamarin-macios/issues/7759

I seem to be able to work around the issue by using

`TART_EXECUTOR_HOST_DIR: "true"`

**Comment by edigaryev** [comment]
I think we've started mounting things directly into the user's home directory since some time ago (even when not using `TART_EXECUTOR_HOST_DIR`), so no symlinks nor whitespaces should be present in the paths anymore.
