### ISSUE TITLE
Multiple jobs: "gitlab-tart-executor": executable file not found in $PATH

### ISSUE THREAD

**Issue by danielbrown2** [cirruslabs/gitlab-tart-executor#40]
Hi,

I'm fairly new to tart and only just got it up and running over the last day. I have one job running nicely now, however if I run multiple I get the following error:
```
Running with gitlab-runner 16.4.1 (d89a789a)
  on finesse-runner uryj6C1v3, system ID: s_eb79cc95f461
Resolving secrets
00:00
Preparing the "custom" executor
00:09
Using Custom executor...
WARNING: Cleanup script failed: failed to start command: exec: "gitlab-tart-executor": executable file not found in $PATH
ERROR: Preparation failed: failed to start command: exec: "gitlab-tart-executor": executable file not found in $PATH
Will be retried in [3](https://gitlab.com/ifosim/finesse/finesse3/-/jobs/5335667566#L3)s ...
Using Custom executor...
WARNING: Cleanup script failed: failed to start command: exec: "gitlab-tart-executor": executable file not found in $PATH
ERROR: Preparation failed: failed to start command: exec: "gitlab-tart-executor": executable file not found in $PATH
Will be retried in 3s ...
Using Custom executor...
WARNING: Cleanup script failed: failed to start command: exec: "gitlab-tart-executor": executable file not found in $PATH
ERROR: Preparation failed: failed to start command: exec: "gitlab-tart-executor": executable file not found in $PATH
Will be retried in 3s ...
ERROR: Job failed (system failure): failed to start command: exec: "gitlab-tart-executor": executable file not found in $PATH
```
If I wait for the started job to finish I restart the failed ones and it runs fine. If anyone wants to have a look at the 

https://gitlab.com/ifosim/finesse/finesse3/-/pipelines/1043388896/builds

3.11 was passing fine by itself before: https://gitlab.com/ifosim/finesse/finesse3/-/jobs/5335622545

config looks like:
```
concurrent = 2
check_interval = 0
shutdown_timeout = 0
[session_server]
 session_timeout = 1800
[[runners]]
 name = "finesse-runner"
 url = "https://gitlab.com/"
 id = ...
 token = ...
 token_obtained_at = ...
 token_expires_at = ...
 executor = "custom"
 builds_dir = "/Users/admin/builds" # directory inside the
 cache_dir = "/Users/admin/cache"
 [runners.feature_flags]
  FF_RESOLVE_FULL_TLS_CHAIN = false
 [runners.custom]
  prepare_exec = "gitlab-tart-executor"
  prepare_args = ["prepare"]
  run_exec = "gitlab-tart-executor"
  run_args = ["run"]
  cleanup_exec = "gitlab-tart-executor"
  cleanup_args = ["cleanup"]
```

**Comment by fkorotkov** [comment]
It seems it even fails to start a VM due to missing `gitlab-tart-executor`. Did you run install the executor binary on all the hosts you have?

```shell
brew install cirruslabs/cli/gitlab-tart-executor
```

**Comment by finebel** [comment]
I started to get the exact same error (after it was working fine initially). After I replaced `gitlab-tart-executor` with the full path (`/opt/homebrew/bin/gitlab-tart-executor`) in `config.toml` it's working now (again).  

Sidenote: I'm not sure but aren't you missing `config_exec` and `config_args` in your `config.toml`?

**Comment by danielbrown2** [comment]
> It seems it even fails to start a VM due to missing `gitlab-tart-executor`. Did you run install the executor binary on all the hosts you have?
> 
> ```shell
> brew install cirruslabs/cli/gitlab-tart-executor
> ```

It does seem to be installed and up to date. Some runners do work, but only if I run one at a time, or I keep retrying others.

> I started to get the exact same error (after it was working fine initially). After I replaced all occurrences of `gitlab-tart-executor` with the full path (`/opt/homebrew/bin/gitlab-tart-executor`) in `config.toml` it's working now (again). Also see https://github.com/cirruslabs/gitlab-tart-executor#local-development.

Good idea! I tried that and now I get another PATH error but only occassionally...
```
Running with gitlab-runner 16.4.1 (d89a789a)
  on finesse-runner uryj6C1v3, system ID: s_eb79cc95f461
Resolving secrets
00:00
Preparing the "custom" executor
00:00
Using Custom executor...
[2](https://gitlab.com/ifosim/finesse/finesse3/-/jobs/5347684554#L2)02[3](https://gitlab.com/ifosim/finesse/finesse3/-/jobs/5347684554#L3)/10/23 09:0[7](https://gitlab.com/ifosim/finesse/finesse3/-/jobs/5347684554#L7):30 Pulling the latest version of containers.ligo.org/finesse/finesse3/sonoma-finesse:v2...
2023/10/23 09:07:30 tart command not found: tart command not found in PATH, make sure Tart is installed
```

All the jobs pass if I keep retrying failed ones:
<img width="503" alt="image" src="https://github.com/cirruslabs/gitlab-tart-executor/assets/1877777/2420298f-6639-40ae-b8a5-682acd38551f">

But the py310 job kept failing for awhile with the PATH error:
<img width="550" alt="image" src="https://github.com/cirruslabs/gitlab-tart-executor/assets/1877777/761dcb2c-7bdc-4a40-a472-d644061f1476">

Given it now can find `gitlab-tart-executor` and no longer `tart`, it feels like the PATH variable just isn't getting set in some cases.

> Sidenote: I'm not sure but aren't you missing `config_exec` and `config_args` in your `config.toml`?
I was just following the config file here (which doesn't seem to have those lines):

https://tart.run/integrations/gitlab-runner/

Should it be included in that example page?

**Comment by danielbrown2** [comment]
I tried the `environment=['PATH=/opt/homebrew/bin:...']` and `pre_build_script='...'` options for the gitlab runner config but that did not resolve the missing `tart`.

If I return `/opt/homebrew/bin/gitlab-tart-executor` -> `gitlab-tart-executor` with the above PATH settings that goes back to failing and complaining `gitlab-tart-executor` isn't in the PATH again.

**Comment by fkorotkov** [comment]
I just recalled that GitLab Runner is still not supporting `zsh` so I wonder if it flakes and is not getting `eval "$(/opt/homebrew/bin/brew shellenv)"` from `~/.zprofile` in order to find binaries. Also how is your GitLab is configured to get started?

Could you please check you `~/.zprofile` and `~/.profile` on the host and maybe try symlinking them or copying one into another. The issue looks bizarre and I see [multiple reports of "executable file not found in" error](https://gitlab.com/search?group_id=9970&project_id=250833&repository_ref=main&scope=issues&search=%22executable+file+not+found+in%22&sort=updated_desc) in the GitLab Runner repository.

**Comment by danielbrown2** [comment]
Yes it could well be the zsh, I was just reading up on some of the same issues.

I just added this to my `/Users/user/Library/LaunchAgents/gitlab-runner.plist`, then `gitlab-runner restart` and now everything works fine 
```
    <key>EnvironmentVariables</key>
    <dict>
        <key>PATH</key>
        <string>/opt/homebrew/bin:$PATH</string>
    </dict>
```

**Comment by finebel** [comment]
@danielbrown2 Thanks for posting this! I experienced the same behaviour and was about to create a new issue.
