### ISSUE TITLE
config --cache-dir appears not to be honoured

### ISSUE THREAD

**Issue by griels** [cirruslabs/gitlab-tart-executor#50]
We have just bought a new SSD (mounted at `/Volumes/SSD/`) for extra storage and are attempting to use it to store Tart cache files.

Passing `['--cache-dir','/Volumes/SSD/tart/cache']` to gitlab-tart-executor config appears not to have any effect - no files are created under this directory.

I also tried setting `TART_EXECUTOR_INTERNAL_CACHE_DIR=/Volumes/SSD/tart/cache` in a wrapper script for gitlab-tart-executor, with no change in behaviour.

If we try to run `tart clone ...` with `TART_HOME` (as mentioned in https://github.com/cirruslabs/tart/issues/221) set to `/Volumes/SSD/tart`as various users, that works fine.

<strike>
Setting TART_HOME in our gitlab-tart-executor wrapper script *does* seem to have an effect, but we then just get the following:

- With 'ignore permissions' set on drive
```
2024/01/05 15:51:44 tart command returned non-zero exit code: "tart/VMStorageLocal.swift:4: Fatal error: 'try!' expression unexpectedly raised an error: Error Domain=NSCocoaErrorDomain Code=513 \"You don’t have permission to save the file “cache” in the folder “tart”.\" UserInfo={NSFilePath=/Volumes/SSD/tart/cache, NSUnderlyingError=0x6000015e4c60 {Error Domain=NSPOSIXErrorDomain Code=1 \"Operation not permitted\"}}"
```
- With 'ignore permissions' unset on drive
```
2024/01/05 15:15:38 Pulling the latest version of gitlab.***.com:5555/infrastructure/build-apple-runner/python-core-updated:DIF-150-python-core-mk3...
2024/01/05 15:15:38 tart command returned non-zero exit code: "Error: You don’t have permission to save the file “gitlab.***.com/5555” in the folder “OCIs”."
```
The runner itself has root permissions, so there's no obvious reason why this would fail when `TART_HOME=/Volumes/SSD/tart tart clone ...` as both a normal user and as root works.

Setting TART_HOME to a different location on the internal drive in our gitlab-tart-executor wrapper script, however, does work.
</strike>
(See comment below, permissions issues are due to Full Disk Permissions having to be enabled for `tart`/`gitlab-tart-executor`).

Is there something we are missing? What diagnostics would be helpful?

Thanks,

Ellis

**Comment by griels** [comment]
Update: it appears the permissions issue was due to MacOS App Permissions, and granting Tart Full Disk Access permissions allowed it to work. So for the time being we are using a wrapper script setting TART_HOME to the external disk.

However, the `--cache-dir` and `TART_EXECUTOR_INTERNAL_CACHE_DIR` settings still seem to have no effect.

**Comment by edigaryev** [comment]
Hello @griels 👋

It's weird that you had to give Tart "Full Disk Access" permission: I've tested the same scenario on my laptop with a USB stick (APFS-formatted) attached to `/Volumes/WHATEVER`, and Tart mounted the volume just fine and was able to write to it.

As for the `--cache-dir`, can you run the `find /Volumes` commands from inside of your pipeline to see if `/Volumes/My Shared Files/cachedir` gets created?

How does your wrapper script looks like? Does it forward all the arguments correctly?

Also, you might be hitting https://github.com/cirruslabs/tart/issues/687 if you're running macOS Sonoma 14.2.
