### ISSUE TITLE
Unable to change mount point of mounted directories

### ISSUE THREAD

**Issue by jlsalmon** [cirruslabs/gitlab-tart-executor#64]
Hi folks,

I just ran into an issue where a build which uses a custom `--builds-dir` argument in the `config` stage failed due to spaces in the path (`/Volumes/My Shared Files/...`) in a component I don't have control over. I'm aware that the mount point can be changed via `mount_virtiofs`, but it doesn't seem to be possible to achieve this at the moment inside a GitLab job.

I tried changing the mountpoint in a `pre_get_sources_script` block in `config.toml`, but unfortunately the GitLab job environment has already been created by this point, and the [buildsdir](https://github.com/cirruslabs/gitlab-tart-executor/blob/main/internal/commands/config/config.go#L104) (and cachedir) are already hard-coded with the default mountpoint.

Would it be possible to provide a way to customise the builds dir on the guest to support non-default mount points? Perhaps with a syntax similar to tart's own `--dir` option, e.g. `--builds-dir=/host/builds:/guest/builds`? 

Perhaps this could also be unified somehow with the `--guest-builds-dir` option? I tried using `--guest-builds-dir` but it's mutually exclusive with `--builds-dir`.

Many thanks in advance 🙏

**Comment by edigaryev** [comment]
> I tried changing the mountpoint in a `pre_get_sources_script` block in `config.toml`, but unfortunately the GitLab job environment has already been created by this point, and the [buildsdir](https://github.com/cirruslabs/gitlab-tart-executor/blob/main/internal/commands/config/config.go#L104) (and cachedir) are already hard-coded with the default mountpoint.

You can work around this by creating a symbolic link:

```shell
ln -s "/Volumes/My Shared Files/buildsdir" /Users/admin/buildsdir
```

...and then passing the `/Users/admin/buildsdir` to the component I don't have control over.

**Comment by jlsalmon** [comment]
@edigaryev many thanks for the suggestion, unfortunately that doesn't seem to be a complete workaround for what I'm currently trying to do, since the component I don't have control over uses `getcwd()` which does not appear to resolve symlinks and returns the real path 🙁
