### ISSUE TITLE
Error: The request timed out - While attemping to pull the latest image.

### ISSUE THREAD

**Issue by dinbtechit** [cirruslabs/gitlab-tart-executor#71]
Recently upgraded the gitlab-tart-executor to version 13. And, build started to fail, due to `Error: The request timed out`.

The build ran for 1hr and showed before showing the timeout error.

![image](https://github.com/cirruslabs/gitlab-tart-executor/assets/17984781/6b74cf51-82b9-4a1e-916c-63036c223437)

---

## Note

1. tart run sonoma-xcode works like a charm. It only fails while running via the gitlab executor. 
2. tart list (Also the latest version of the image already exist on the machine)
![image](https://github.com/cirruslabs/gitlab-tart-executor/assets/17984781/c279d69e-b100-4672-80d3-14f1d52266de)

Thank you,

**Comment by fkorotkov** [comment]
Could you please try to `tart pull ghcr.io/cirruslabs/macos-sonoma-xcode:latest` on the machine? This image just got updated and it seems your host is failing to download it.

**Comment by dinbtechit** [comment]
> Could you please try to `tart pull ghcr.io/cirruslabs/macos-sonoma-xcode:latest` on the machine? This image just got updated and it seems your host is failing to download it.

@fkorotkov - The issue got resolved after manually pulling the image. Thank you so much
