### ISSUE TITLE
Error when running jobs with ubuntu image

### ISSUE THREAD

**Issue by 0xff8** [cirruslabs/gitlab-tart-executor#95]
Hi guys,

When I run my job with any macOS image everything works as expected. But when I am trying to execute the same job using linux image - job fails. I assume the problem is in the `config_exec` step and particularly with `gitlab-tart-executor config` . Is there a way to set `build_dir` and `cache_dir` via environment variables ? Or set it in `config.toml` to some value that will work for both linux and macOS images ? 

#### .gitlab-ci.yaml configuration:
```yaml
virtual-machine-arm64:
  stage: test
  image: ghcr.io/cirruslabs/ubuntu-runner-arm64:22.04
  variables:
    TART_EXECUTOR_SHELL: "/usr/bin/bash"
  tags: [ "arm64" ]
  script:
    - lsb_release -a
    - whoami
```

#### Error:
```
....
Using Custom executor...
2024/11/30 19:03:15 Pulling the latest version of ghcr.io/cirruslabs/ubuntu-runner-arm64:22.04...
2024/11/30 19:25:02 Cloning and configuring a new VM...
2024/11/30 19:25:02 Waiting for the VM to boot and be SSH-able...
2024/11/30 19:25:09 Was able to SSH!
2024/11/30 19:25:09 VM is ready.

Preparing environment
00:00
Running on ubuntu...

Getting source from Git repository
00:00
mkdir: cannot create directory ‘/private’: Permission denied
2024/11/30 19:25:09 Process exited with status 1
```

Any suggestions are welcomed :)

**Comment by 0xff8** [comment]
hi @fkorotkov ,  
  
Thanks for the answer!   
Currently, we have a virtual machine runner for amd64 VMs (based on KVM) and it is very flexible we can run any OS (Linux, Windows, BSDs)  just specifying `image: win2019` field in the `.gitlab-ci.yaml` (except macOS by obvious reasons) 
We would like to have something similar for ARM64 platform , where developers can run various VMs using different images. 
The best solution for us would be either having an algorithm in `config` script that can detect what image is being run (MacOS / Linux / Windows ) and then adjust the paths automatically. 
Also, less convenient way to us, but more error prone is to pass some env variables defined for a job / globally  like `TART_EXECUTOR_BUILD_DIR` / `TART_EXECUTOR_CACHE_DIR` and define the correct values there. 

Right now I can only define these values as parameters and they will only be read once runner is started:
```golang
	cmd.PersistentFlags().StringVar(&buildsDir, "builds-dir", "",
		"path to a directory on host to use for storing builds, automatically mounts that directory "+
			"to the guest VM, mutually exclusive with \"--guest-builds-dir\"")
	cmd.PersistentFlags().StringVar(&cacheDir, "cache-dir", "",
		"path to a directory on host to use for caching purposes, automatically mounts that directory "+
			"to the guest VM, mutually exclusive with \"--guest-cache-dir\"")
	cmd.PersistentFlags().StringVar(&guestBuildsDir, "guest-builds-dir", "",
		"path to a directory in guest to use for storing builds, useful when mounting a block device "+
			"via \"--disk\" command-line argument (mutually exclusive with \"--builds-dir\")")
	cmd.PersistentFlags().StringVar(&guestCacheDir, "guest-cache-dir", "",
		"path to a directory in guest to use for caching purposes, useful when mounting a block device "+
			"via \"--disk\" command-line argument (mutually exclusive with \"--cache-dir\")")
```

**Comment by edigaryev** [comment]
Hi @0xff8,

Please check out the [latest `1.21.0` release](https://github.com/cirruslabs/gitlab-tart-executor/releases/tag/1.21.0), which should work well with linux VMs 🐧 

The only thing that you should probably keep in your CI configuration for Linux jobs is `TART_EXECUTOR_SHELL: "/usr/bin/bash"`.
